mutation appUserInfo($param: AppUserSaveIn!) {
  appUser(param: $param) {
    id
  }
}

query appUserAll($param: QueryListParam) {
  appUserAll(param: $param) {
    ...AppUser
  }
}

fragment AppUser on AppUser {
  id
  nickname
  realName
  openid
  phone
}
