# login
query login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    ...LoginUser
  }
}

# codeToSession
query codeToSession($code: String!) {
  codeToSession(code: $code) {
    ...CodeToSessionGql
  }
}

fragment LoginUser on AuthGql {
  id
  token
}

fragment CodeToSessionGql on CodeToSessionGql {
  openid
  unionid
  sessionKey
  phone
  id
  token
  nickname
}

query wxDataDecoded(
  $cloudID: String
  $iv: String
  $encryptedData: String
  $sessionKey: String
  $openid: String
) {
  wxDataDecoded(
    cloudID: $cloudID
    iv: $iv
    encryptedData: $encryptedData
    sessionKey: $sessionKey
    openid: $openid
  ) {
    purePhoneNumber
    token
    id
  }
}
